import React from 'react'
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview} from '../utils';
import {getRandomPrompt} from '../utils';
import { FormField, Loader } from '../components';

const CreatePost = () => {
  const navigate = useNavigate();
  const [form , setForm] = useState({
    name: '',
    prompt: '',
    photo : '',
  });

  const [generetingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]" >Home</h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">Browse through a collection of imaginetive and visually stunning images generated by DALL-E AI</p>
      </div>
    </section>
  )
}

export default CreatePost